package smartdns

import (
	"fmt"
	"net"
	"sort"
	"strings"

	"github.com/morain/5gws/internal/config"
	"github.com/morain/5gws/internal/rules"
)

func Config(cfg config.Config, norm rules.Normalized) (string, error) {
	plan, err := buildPlan(norm)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("# Generated by 5gws. Do not edit.\n")
	fmt.Fprintf(&b, "bind %s -group overseas_private\n", cfg.DNS.ListenUDP)
	fmt.Fprintf(&b, "bind-tcp %s -group overseas_private\n", cfg.DNS.ListenTCP)
	fmt.Fprintf(&b, "bind-tls %s -group overseas_private\n", cfg.DNS.ListenDOT)
	if cfg.DNS.ListenPublicDOT != "" {
		fmt.Fprintf(&b, "bind-tls %s -group overseas_public -no-rule-addr\n", cfg.DNS.ListenPublicDOT)
	}
	fmt.Fprintf(&b, "bind-cert-file %s/fullchain.pem\n", cfg.DNS.CertDir)
	fmt.Fprintf(&b, "bind-cert-key-file %s/privkey.pem\n", cfg.DNS.CertDir)
	fmt.Fprintf(&b, "cache-size %d\n", cfg.DNS.CacheSize)
	b.WriteString("response-mode fastest-response\n")
	b.WriteString("force-AAAA-SOA yes\n")
	b.WriteString("force-qtype-SOA 64 65\n")
	for _, upstream := range cfg.DNS.UpstreamsCN {
		fmt.Fprintf(&b, "server %s -group cn -exclude-default-group\n", upstream)
	}
	for _, upstream := range cfg.DNS.UpstreamsOverseasPrivate {
		fmt.Fprintf(&b, "server %s -group overseas_private -exclude-default-group\n", upstream)
	}
	gateway := net.ParseIP(cfg.Network.GatewayIP).String()
	for _, upstream := range cfg.DNS.UpstreamsOverseasPublic {
		fmt.Fprintf(&b, "server %s -group overseas_public -exclude-default-group\n", upstream)
	}
	for _, rule := range plan.DNSPoolRules {
		fmt.Fprintf(&b, "nameserver /%s/%s\n", rule.Domain, rule.Pool)
	}
	for _, domain := range plan.GatewayDomains {
		fmt.Fprintf(&b, "address /%s/%s\n", domain, gateway)
	}
	return b.String(), nil
}

type dnsPoolRule struct {
	Domain string
	Pool   string
}

type renderPlan struct {
	GatewayDomains []string
	DNSPoolRules   []dnsPoolRule
}

func buildPlan(norm rules.Normalized) (renderPlan, error) {
	seen := map[string]bool{}
	poolSeen := map[string]bool{}
	var poolRules []dnsPoolRule
	for _, rule := range norm.Rules {
		if len(rule.DomainKeyword) > 0 || len(rule.DomainRegex) > 0 || len(rule.IPCIDR) > 0 || len(rule.RuleSet) > 0 {
			return renderPlan{}, fmt.Errorf("rule %q uses matchers that smartdns-rs cannot represent", rule.Name)
		}
		for _, value := range rule.Domain {
			domain := normalizeDomain(value)
			if err := addDomainRule(rule, domain, seen, poolSeen, &poolRules); err != nil {
				return renderPlan{}, err
			}
		}
		for _, value := range rule.DomainSuffix {
			domain := normalizeDomain(value)
			if err := addDomainRule(rule, domain, seen, poolSeen, &poolRules); err != nil {
				return renderPlan{}, err
			}
		}
	}
	gatewayDomains := make([]string, 0, len(seen))
	for domain := range seen {
		gatewayDomains = append(gatewayDomains, domain)
	}
	sort.Strings(gatewayDomains)
	sort.Slice(poolRules, func(i, j int) bool {
		if poolRules[i].Domain == poolRules[j].Domain {
			return poolRules[i].Pool < poolRules[j].Pool
		}
		return poolRules[i].Domain < poolRules[j].Domain
	})
	return renderPlan{GatewayDomains: gatewayDomains, DNSPoolRules: poolRules}, nil
}

func addDomainRule(rule rules.Rule, domain string, gatewaySeen, poolSeen map[string]bool, poolRules *[]dnsPoolRule) error {
	if domain == "" {
		return fmt.Errorf("rule %q has empty domain matcher", rule.Name)
	}
	if rule.DNSOnly() {
		key := rule.DNSPool + "\x00" + domain
		if !poolSeen[key] {
			*poolRules = append(*poolRules, dnsPoolRule{Domain: domain, Pool: rule.DNSPool})
			poolSeen[key] = true
		}
		return nil
	}
	if rule.Gateway() {
		gatewaySeen[domain] = true
	}
	return nil
}

func normalizeDomain(value string) string {
	return strings.ToLower(strings.TrimPrefix(strings.TrimSuffix(strings.TrimSpace(value), "."), "."))
}
