package smartdns

import (
	"fmt"
	"net"
	"sort"
	"strings"

	"github.com/morain/5gws/internal/config"
	"github.com/morain/5gws/internal/rules"
)

const cacheFile = "/var/log/smartdns/smartdns.cache"

type Output struct {
	Config string
	Files  map[string]string
}

func Config(cfg config.Config, norm rules.Normalized) (string, error) {
	out, err := Generate(cfg, norm)
	return out.Config, err
}

func Generate(cfg config.Config, norm rules.Normalized) (Output, error) {
	return GenerateAt(cfg, norm, cfg.System.StateDir+"/rendered/smartdns")
}

func GenerateAt(cfg config.Config, norm rules.Normalized, configDir string) (Output, error) {
	plan, err := buildPlan(norm)
	if err != nil {
		return Output{}, err
	}
	poolNames := make(map[string]bool)
	for _, pool := range cfg.DNS.Pools() {
		poolNames[pool.Name] = true
	}
	for _, rule := range plan.DNSPoolRules {
		if !poolNames[rule.Pool] {
			return Output{}, fmt.Errorf("rule references unknown dns pool %q", rule.Pool)
		}
	}
	var b strings.Builder
	b.WriteString("# Generated by 5gws. Do not edit.\n")
	fmt.Fprintf(&b, "bind %s\n", cfg.DNS.ListenUDP)
	fmt.Fprintf(&b, "bind-tcp %s\n", cfg.DNS.ListenTCP)
	fmt.Fprintf(&b, "bind-tls %s\n", cfg.DNS.ListenDOT)
	if cfg.DNS.ListenPublicDOT != "" {
		fmt.Fprintf(&b, "bind-tls %s\n", cfg.DNS.ListenPublicDOT)
	}
	fmt.Fprintf(&b, "bind-cert-file %s\n", cfg.DNS.CertFile)
	fmt.Fprintf(&b, "bind-cert-key-file %s\n", cfg.DNS.KeyFile)
	fmt.Fprintf(&b, "cache-size %d\n", cfg.DNS.CacheSize)
	b.WriteString("cache-persist yes\n")
	fmt.Fprintf(&b, "cache-file %s\n", cacheFile)
	b.WriteString("prefetch-domain yes\n")
	b.WriteString("response-mode fastest-response\n")
	b.WriteString("force-AAAA-SOA yes\n")
	b.WriteString("force-qtype-SOA 64 65\n")
	for _, upstream := range cfg.DNS.UpstreamsCN {
		fmt.Fprintf(&b, "server %s -group cn -exclude-default-group\n", upstream)
	}
	for _, upstream := range cfg.DNS.UpstreamsOverseasPrivate {
		fmt.Fprintf(&b, "server %s -group overseas_private\n", upstream)
	}
	gateway := net.ParseIP(cfg.Network.GatewayIP).String()
	for _, upstream := range cfg.DNS.UpstreamsOverseasPublic {
		fmt.Fprintf(&b, "server %s -group overseas_public -exclude-default-group\n", upstream)
	}
	for _, pool := range cfg.DNS.CustomPools {
		for _, upstream := range pool.Upstreams {
			fmt.Fprintf(&b, "server %s -group %s -exclude-default-group\n", upstream, pool.Name)
		}
	}
	files := make(map[string]string)
	for _, pool := range cfg.DNS.Pools() {
		var domains []string
		for _, rule := range plan.DNSPoolRules {
			if rule.Pool == pool.Name {
				domains = append(domains, rule.Domain)
			}
		}
		if len(domains) == 0 {
			continue
		}
		name := "pool_" + pool.Name
		path := configDir + "/" + name + ".list"
		files[name+".list"] = strings.Join(domains, "\n") + "\n"
		fmt.Fprintf(&b, "domain-set -name %s -type list -file %s\n", name, path)
		fmt.Fprintf(&b, "nameserver /domain-set:%s/%s\n", name, pool.Name)
	}
	if len(plan.GatewayDomains) > 0 {
		path := configDir + "/gateway.list"
		files["gateway.list"] = strings.Join(plan.GatewayDomains, "\n") + "\n"
		fmt.Fprintf(&b, "domain-set -name gateway -type list -file %s\n", path)
		fmt.Fprintf(&b, "address /domain-set:gateway/%s\n", gateway)
	}
	return Output{Config: b.String(), Files: files}, nil
}

type dnsPoolRule struct {
	Domain string
	Pool   string
}

type renderPlan struct {
	GatewayDomains []string
	DNSPoolRules   []dnsPoolRule
}

func buildPlan(norm rules.Normalized) (renderPlan, error) {
	gatewaySeen := map[string]bool{}
	poolSeen := map[string]bool{}
	decided := map[string]bool{}
	var poolRules []dnsPoolRule
	for _, rule := range norm.Rules {
		if len(rule.DomainKeyword) > 0 || len(rule.DomainRegex) > 0 || len(rule.IPCIDR) > 0 || len(rule.RuleSet) > 0 {
			return renderPlan{}, fmt.Errorf("rule %q uses matchers that smartdns-rs cannot represent", rule.Name)
		}
		for _, value := range rule.Domain {
			domain := normalizeDomain(value)
			if err := addDomainRule(rule, domain, decided, gatewaySeen, poolSeen, &poolRules); err != nil {
				return renderPlan{}, err
			}
		}
		for _, value := range rule.DomainSuffix {
			domain := normalizeDomain(value)
			if err := addDomainRule(rule, domain, decided, gatewaySeen, poolSeen, &poolRules); err != nil {
				return renderPlan{}, err
			}
		}
	}
	gatewayDomains := make([]string, 0, len(gatewaySeen))
	for domain := range gatewaySeen {
		gatewayDomains = append(gatewayDomains, domain)
	}
	sort.Strings(gatewayDomains)
	sort.Slice(poolRules, func(i, j int) bool {
		if poolRules[i].Domain == poolRules[j].Domain {
			return poolRules[i].Pool < poolRules[j].Pool
		}
		return poolRules[i].Domain < poolRules[j].Domain
	})
	return renderPlan{GatewayDomains: gatewayDomains, DNSPoolRules: poolRules}, nil
}

func addDomainRule(rule rules.Rule, domain string, decided, gatewaySeen, poolSeen map[string]bool, poolRules *[]dnsPoolRule) error {
	if domain == "" {
		return fmt.Errorf("rule %q has empty domain matcher", rule.Name)
	}
	if decided[domain] {
		return nil
	}
	if rule.DNSOnly() {
		key := rule.DNSPool + "\x00" + domain
		if !poolSeen[key] {
			*poolRules = append(*poolRules, dnsPoolRule{Domain: domain, Pool: rule.DNSPool})
			poolSeen[key] = true
		}
		decided[domain] = true
		return nil
	}
	if rule.Gateway() {
		gatewaySeen[domain] = true
		decided[domain] = true
	}
	return nil
}

func normalizeDomain(value string) string {
	return strings.ToLower(strings.TrimPrefix(strings.TrimSuffix(strings.TrimSpace(value), "."), "."))
}
